version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "axios"
        update-schedule: "weekly"
        versioning-strategy: "widen"
      - dependency-name: "cheerio"
        update-schedule: "weekly"
        versioning-strategy: "widen"
      - dependency-name: "compression"
        update-schedule: "weekly"
        versioning-strategy: "widen"
      - dependency-name: "cors"
        update-schedule: "weekly"
        versioning-strategy: "widen"
      - dependency-name: "express"
        update-schedule: "weekly"
        versioning-strategy: "widen"
      - dependency-name: "express-rate-limit"
        update-schedule: "weekly"
        versioning-strategy: "widen"
      - dependency-name: "helmet"
        update-schedule: "weekly"
        versioning-strategy: "widen"
      - dependency-name: "node-cache"
        update-schedule: "weekly"
        versioning-strategy: "widen"
      - dependency-name: "node-cron"
        update-schedule: "weekly"
        versioning-strategy: "widen"
