version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        dependency-name: "axios"
        versions: ["^1.x.x"]
      - dependency-type: "direct"
        dependency-name: "cheerio"
        versions: ["^1.x.x"]
      - dependency-type: "direct"
        dependency-name: "compression"
        versions: ["^1.x.x"]
      - dependency-type: "direct"
        dependency-name: "cors"
        versions: ["^2.x.x"]
      - dependency-type: "direct"
        dependency-name: "express"
        versions: ["^4.x.x"]
      - dependency-type: "direct"
        dependency-name: "express-rate-limit"
        versions: ["^7.x.x"]
      - dependency-type: "direct"
        dependency-name: "helmet"
        versions: ["^7.x.x"]
      - dependency-type: "direct"
        dependency-name: "node-cache"
        versions: ["^5.x.x"]
      - dependency-type: "direct"
        dependency-name: "node-cron"
        versions: ["^3.x.x"]
