version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "axios"
      - dependency-name: "cheerio"
      - dependency-name: "compression"
      - dependency-name: "cors"
      - dependency-name: "express"
      - dependency-name: "express-rate-limit"
      - dependency-name: "helmet"
      - dependency-name: "node-cache"
      - dependency-name: "node-cron"
